In [2]:
import os
import pandas as pd
import numpy as np
import re
import scipy.io

In [3]:
root_dir = "C:/Users/VukadinoviM/Documents/BrainReg/data"

In [26]:
cnt=0
for file in os.listdir(root_dir):
    for file_name in os.listdir(os.path.join(root_dir, file)):
        if "lead" in file_name:
            cnt+=1
#            os.rename(os.path.join(root_dir, file, file_name),
#                           os.path.join(root_dir, file, "hull_rh."))
            break

In [27]:
cnt

0

Saanity check

In [83]:
cnt=0
b=None
for file in os.listdir(root_dir):
    if os.path.exists(os.path.join(root_dir, file, "lead_coords.mat")):
            cnt+=1
            a = scipy.io.loadmat(os.path.join(root_dir, file, "lead_coords.mat")) 
            np_ar = None
            try:
                np.save(os.path.join(root_dir, file, "load_coords.npy"),
                        a['elecmatrix'])
                
            except:
                np.save(os.path.join(root_dir, file, "load_coords.npy"), np.stack(a['CortElecLoc'][0]).reshape(8,3))

In [81]:
a['CortElecLoc'][0]

array([array([[ 47.97600965, -31.71920633,  44.79766576]]),
       array([[ 48.97600941, -40.71920635,  43.79766561]]),
       array([[ 51.97600868, -48.7192064 ,  40.79766516]]),
       array([[ 53.97600814, -57.71920643,  37.79766486]]),
       array([[ 54.97600777, -65.71920644,  34.79766471]]),
       array([[ 55.97600727, -73.71920646,  29.79766455]]),
       array([[ 55.97600695, -81.71920646,  24.79766455]]),
       array([[ 44.97601032, -21.71920628,  46.79766621]])], dtype=object)

array([[ 47.97600965, -31.71920633,  44.79766576],
       [ 48.97600941, -40.71920635,  43.79766561],
       [ 51.97600868, -48.7192064 ,  40.79766516],
       [ 53.97600814, -57.71920643,  37.79766486],
       [ 54.97600777, -65.71920644,  34.79766471],
       [ 55.97600727, -73.71920646,  29.79766455],
       [ 55.97600695, -81.71920646,  24.79766455],
       [ 44.97601032, -21.71920628,  46.79766621]])

In [147]:
pd.DataFrame.from_dict({"idx":ids, "pin_locations": pin_locations}).to_csv("pin_labels.csv")

In [148]:
df = pd.read_csv("pin_labels.csv")

<ipython-input-165-fd3eb360c135>:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(df['pin_locations'][0].split('\n')[1])


ValueError: string size must be a multiple of element size

In [161]:
df['pin_locations'][0]

'[[-50.88806927 -79.15765357 -21.03157568]\n [-35.05228251  54.95319629   1.91240382]\n [ 31.89383894 -81.80937266 -19.48378015]\n [ 46.40907854  49.41102052   0.47815299]]'

In [121]:
scipy.io.loadmat(os.path.join(root_dir, "DBS_bG72", "pin_tips.mat"))

ValueError: Mat 4 mopt wrong format, byteswapping problem?

In [30]:
import shutil
cnt=0

for file in os.listdir(root_dir):
    name_found=False
    for path, subdirs, files in os.walk(os.path.join(root_dir,file)):
        for name in files:
            if "lead" in os.path.join(path, name):
                cnt+=1
                name_found=True
                shutil.copyfile(os.path.join(path, name),
                                os.path.join(root_dir, file,"lead_coords.mat"))
                break
        if name_found:
            break

In [29]:
cnt

48

In [102]:
len(set(ss))

82

In [47]:
labels = "C:/Users/VukadinoviM/Documents/BrainReg/data/labels.csv"
df = pd.read_csv(labels)

In [59]:
for idx in df.idx:
    a = os.path.join(os.path.join(root_dir,idx),"electrode_locations")
    if os.path.exists(os.path.join(a,"PinTips.mat"))==False:
        print(a)

C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG17\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG27\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG29\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG38\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG68\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bS05\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bT01\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bT05\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bT07\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bT08\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_IG01\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_IT01\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_IT02\electrode_locations
C:/Users/VukadinoviM/Documents/BrainRe

In [38]:
p = []
cnt=0
for name in os.listdir(root_dir):
    path=os.path.join(root_dir, name)
    a = os.path.join(path, "preop_ct.nii")
    b = os.path.join(path, "electrode_locations")
    if os.path.exists(a) and os.path.exists(b):
        p.append(name)
    #if os.path.exists(os.path.join(path, "rpreop_ct.nii")):
    #    p.append(name)

In [21]:
p = []
for name in os.listdir(root_dir):
    path=os.path.join(root_dir, name)
    for g in os.listdir(path):
        if os.path.isdir(os.path.join(path,g)):
            print (os.path.join(path,g))


C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG01\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG02\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG02\Electrode_Locations_Andrew
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG03\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG03\Electrode_Locations_Andrew
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG03\Electrode_Locations_Andrew_Redo
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG06\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG06\Electrode_Locations_Andrew
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG06\Electrode_Locations_Andrew_Redo
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG09\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG09\Electrode_Locations_Andrew
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG10\electrode_locations
C:/Users/VukadinoviM/Documents/BrainReg/data\DBS_bG10\Electr

In [23]:
g.split(".")[1]

'nii'

pre_opCT